language: python - "2.7"

# before_install will simply setup a conda enviroment for installing python packages, if you
# have project dependencies it's usually recommended to go this route.
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    # - sudo rm -rf /dev/shm
    # - sudo ln -s /run/shm /dev/shm

install:
    - conda install --yes python="2.7" sphinx
    # - pip install --user travis-sphinx
    - pip install --user git+https://github.com/Syntaf/travis-sphinx.git
    - pip install --user sphinx_rtd_theme
    - pip install --user sphinx_tabs

script:
    - travis-sphinx build -s .

after_success:
    # Add our CNAME file as the deploy tool completely
    # overwrites the existing gh-pages branch.
    - echo 'docs.roomify.us' > ./doc/build/CNAME
    # Run the deploy process.
    - travis-sphinx deploy
